# Generated by Django 5.1.2 on 2024-10-17 20:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Регион')),
                ('code', models.CharField(max_length=3, verbose_name='Код региона')),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Источник опубликования')),
                ('url_address', models.CharField(max_length=60, verbose_name='Адрес источника опубликования')),
            ],
            options={
                'db_table': 'source',
            },
        ),
        migrations.CreateModel(
            name='PublishedNPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название НПА')),
                ('number', models.CharField(max_length=10, verbose_name='Номер НПА')),
                ('publish_date', models.DateField(verbose_name='Дата опубликования')),
                ('write_date', models.DateField(verbose_name='Дата подписания НПА')),
                ('date_now', models.DateField(default=datetime.datetime.now)),
                ('link_to_download', models.CharField(max_length=100, verbose_name='Ссылка на скачивание')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_npas', to='pravo.region')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_npas', to='pravo.source')),
            ],
            options={
                'db_table': 'published_npa',
            },
        ),
    ]
