# Generated by Django 5.1.2 on 2024-11-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishednpa',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Если на право.гов.ру?'),
        ),
    ]
