# Generated by Django 5.1.2 on 2024-11-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravo', '0002_publishednpa_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishednpa',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Есть ли на право.гов.ру?'),
        ),
    ]
