# Generated by Django 5.1.2 on 2024-12-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravo', '0003_alter_publishednpa_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishednpa',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название НПА'),
        ),
    ]
