# Generated by Django 5.1.2 on 2024-12-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravo', '0004_alter_publishednpa_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishednpa',
            name='name',
            field=models.CharField(verbose_name='Название НПА'),
        ),
    ]
