# Generated by Django 5.1.2 on 2024-12-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravo', '0008_alter_publishednpa_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishednpa',
            name='link_to_download',
            field=models.CharField(verbose_name='Ссылка на скачивание'),
        ),
    ]
