# Generated by Django 5.1.2 on 2024-12-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravo', '0009_alter_publishednpa_link_to_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishednpa',
            name='name',
            field=models.CharField(verbose_name='Название НПА'),
        ),
    ]
