# Generated by Django 5.1.2 on 2025-02-28 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravo', '0010_alter_publishednpa_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishednpa',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AlterField(
            model_name='publishednpa',
            name='date_now',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата загрузки на портал'),
        ),
    ]
