# Generated by Django 5.1.2 on 2025-04-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravo', '0011_alter_publishednpa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Источник опубликования'),
        ),
    ]
