# Generated by Django 5.1.2 on 2025-06-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pravo', '0012_alter_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishednpa',
            name='link_to_download',
            field=models.CharField(max_length=255, verbose_name='Ссылка на скачивание'),
        ),
        migrations.AlterField(
            model_name='publishednpa',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название НПА'),
        ),
    ]
